# Generated by Django 3.2.5 on 2021-07-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0008_alter_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='app03.Author'),
        ),
    ]
